/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktest_hellojni */

#ifndef _Included_com_example_ndktest_hellojni
#define _Included_com_example_ndktest_hellojni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktest_hellojni
 * Method:    NDKTestFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktest_hellojni_NDKTestFromJNI
  (JNIEnv *, jobject);

void Java_com_example_ndktest_hellojni_readFromAssets(JNIEnv* env,jclass tis
,jobject assetManager,jstring filename)
#ifdef __cplusplus
}
#endif
#endif
